# Generated by Django 5.2.9 on 2026-07-02 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STATION_LOGIN', 'Station Login'), ('STATION_LOGOUT', 'Station Logout'), ('LOGIN_FAILED', 'Login Failed'), ('VOTE_CAST', 'Vote Cast'), ('RATE_LIMITED', 'Rate Limited'), ('VOTER_CREATED', 'Voter ID Created'), ('VOTER_DELETED', 'Voter ID Deleted'), ('ERROR', 'Error')], max_length=20)),
                ('station_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_number', models.IntegerField()),
                ('district_name', models.CharField(max_length=100)),
                ('division_code', models.CharField(max_length=5)),
                ('division_name', models.CharField(max_length=100)),
                ('login_key', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'polling_station',
            },
        ),
        migrations.CreateModel(
            name='TempVoterId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('has_voted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'temp_voter_id',
            },
        ),
        migrations.AddField(
            model_name='vote',
            name='polling_station',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='station_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='voted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
