# Generated by Django 5.2.9 on 2026-09-29 15:20

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_polling_station_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainBlock',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('block_index', models.IntegerField(db_index=True, unique=True)),
                ('station_code', models.CharField(max_length=30)),
                ('voted_at_iso', models.CharField(max_length=50)),
                ('ballot_hash', models.CharField(max_length=64)),
                ('previous_hash', models.CharField(max_length=64)),
                ('block_hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'blockchain_block',
                'ordering': ['block_index'],
            },
        ),
    ]
