# Generated by Django 5.2.9 on 2025-12-04 08:19

from django.db import migrations, models
import django_mongodb_backend.fields

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic_number', models.CharField(max_length=20, unique=True, verbose_name='National Identity Card Number')),
                ('full_legal_name', models.CharField(max_length=200)),
                ('ballot_display_name_si', models.CharField(max_length=200, verbose_name='Name in Sinhala for ballot sorting')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('nomination_type', models.CharField(choices=[('Recognized Party', 'Recognized Party'), ('Independent Group', 'Independent Group')], max_length=50)),
                ('political_party', models.CharField(max_length=200, verbose_name='Political Party')),
                ('party_symbol', models.ImageField(upload_to='party_symbols/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
