# Generated by Django 5.2.9 on 2025-12-04 09:35

import candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='dob',
            field=models.DateField(validators=[candidates.models.validate_age], verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nic_number',
            field=models.CharField(help_text='Enter the unique NIC number.', max_length=20, unique=True, verbose_name='National Identity Card Number'),
        ),
    ]